# Netlify Configuration for Beta Subdomain (Next.js SSR)
# Deploy to: beta.findmyweddingvendor.com

[build]
  command = "npm install && npm run build:next"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev --legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Use Netlify's Next.js Runtime for SSR support
[[plugins]]
  package = "@netlify/plugin-nextjs"

# SEO optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Headers for better security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache Next.js static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
