interface TimelineFAQProps {
  stateSlug?: string;
  citySlug?: string;
  className?: string;
}

const TimelineFAQ = ({ stateSlug, citySlug, className = "" }: TimelineFAQProps) => {
  // Format state and city names for display
  const formatName = (slug?: string) => {
    if (!slug) return "";
    return slug
      .split("-")
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  };

  const stateName = formatName(stateSlug);
  const cityName = formatName(citySlug);
  const locationText = cityName && stateName ? `${cityName}, ${stateName}` : stateName;

  // Generate location-specific FAQs
  const getFAQs = () => {
    const baseFAQs = [
      {
        question: `What is a wedding timeline${locationText ? ` for ${locationText}` : ""}?`,
        answer: `A wedding timeline${locationText ? ` for ${locationText}` : ""} is a detailed schedule that outlines all the important tasks and events leading up to and including your wedding day. It helps you stay organized, ensures you don't miss any critical deadlines, and keeps everyone involved on the same page.`
      },
      {
        question: "When should I start planning my wedding timeline?",
        answer: "Ideally, you should start planning your wedding timeline as soon as you get engaged, especially if you have a wedding date in mind. Most wedding planners recommend beginning the timeline process 12-18 months before your wedding date, but our generator can help you create a customized timeline no matter how much time you have left."
      },
      {
        question: `How detailed should my wedding timeline${locationText ? ` for ${locationText}` : ""} be?`,
        answer: `Your wedding timeline${locationText ? ` for ${locationText}` : ""} should be as detailed as possible, including all major planning milestones (booking vendors, sending invitations, etc.) as well as a minute-by-minute schedule for the wedding day itself. Our generator helps you create both a long-term planning timeline and a detailed day-of schedule.`
      },
      {
        question: "Can I customize the timeline generated by this tool?",
        answer: "Absolutely! Our wedding timeline generator creates a personalized timeline based on your wedding date and preferences, but you can always add, remove, or modify events to suit your specific needs. The timeline is fully customizable to accommodate your unique wedding plans."
      },
      {
        question: `What are the key milestones to include in a ${locationText ? `${locationText} ` : ""}wedding timeline?`,
        answer: `Key milestones for a ${locationText ? `${locationText} ` : ""}wedding timeline include: setting a budget, booking your venue, selecting vendors, sending save-the-dates and invitations, planning the rehearsal dinner, creating a day-of schedule, and following up with thank-you notes after the wedding. Our generator includes all these milestones and more.`
      }
    ];

    // Add location-specific FAQs if applicable
    if (locationText) {
      baseFAQs.push({
        question: `Are there any special considerations for weddings in ${locationText}?`,
        answer: `Weddings in ${locationText} may have unique considerations such as seasonal weather patterns, local venue availability, and regional traditions. Our timeline generator takes these factors into account to help you plan a successful wedding in ${locationText}.`
      });
      
      baseFAQs.push({
        question: `How far in advance should I book vendors for my ${locationText} wedding?`,
        answer: `For weddings in ${locationText}, it's recommended to book popular vendors like venues, photographers, and caterers 12-18 months in advance, especially during peak wedding season. Our timeline generator will remind you of these important booking deadlines.`
      });
    }

    return baseFAQs;
  };

  const faqs = getFAQs();

  // Schema.org FAQ Page markup
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqs.map(faq => ({
      "@type": "Question",
      "name": faq.question,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.answer
      }
    }))
  };

  return (
    <div className={`mt-12 ${className}`}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      
      <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
      
      <div className="space-y-6">
        {faqs.map((faq, index) => (
          <div key={index} className="bg-white rounded-lg shadow-sm p-6">
            <h3 className="text-lg font-semibold mb-2">{faq.question}</h3>
            <p className="text-gray-600">{faq.answer}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default TimelineFAQ;
