// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types-extension';

// Support both Vite (import.meta.env) and Next.js (process.env) environments
// In Next.js builds, process.env is available and prefixed with NEXT_PUBLIC_
// In Vite, import.meta.env is available and prefixed with VITE_
const getEnvVar = (fallback: string): string => {
  // Try Next.js environment variables first (for build-time)
  if (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_SUPABASE_URL) {
    return process.env.NEXT_PUBLIC_SUPABASE_URL;
  }
  if (typeof process !== 'undefined' && process.env?.VITE_SUPABASE_URL) {
    return process.env.VITE_SUPABASE_URL;
  }
  // Try Vite environment variables (for dev)
  if (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_URL) {
    return import.meta.env.VITE_SUPABASE_URL;
  }
  return fallback;
};

// Use publishable key (sb_publishable_...) — replaces deprecated legacy JWT anon key.
// Edge Functions must be deployed with --no-verify-jwt to accept this key.
// See: https://github.com/orgs/supabase/discussions/42949
const getPublishableKey = (fallback: string): string => {
  if (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) {
    return process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
  }
  if (typeof process !== 'undefined' && process.env?.VITE_SUPABASE_PUBLISHABLE_KEY) {
    return process.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  }
  if (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY) {
    return import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  }
  return fallback;
};

const SUPABASE_URL = getEnvVar('https://wpbdveyuuudhmwflrmqw.supabase.co');
const SUPABASE_PUBLISHABLE_KEY = getPublishableKey('sb_publishable_FFHBhR9e1yxbt-rA_JfGsw_HtyEgdoG');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
